name: 'My GitHub Action'
description: 'An example GitHub Action implemented in TypeScript'
inputs:
  myInput:
    description: 'An example input'
    required: true
runs:
  using: 'node12'
  main: 'dist/main.js'